import streamlit as st
import sys
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent.parent))
import api_client as api

def _format_ts(ts_str):
    if not ts_str:
        return "—"
    try:
        return datetime.fromisoformat(ts_str).strftime("%d %b %Y, %I:%M %p")
    except:
        return ts_str

def show():
    st.markdown('<div class="page-header"><h1>AI Generation History</h1><p>Past negotiation strategies and letters generated by FinRelief AI</p></div>', unsafe_allow_html=True)

    col_refresh, _ = st.columns([1, 5])
    with col_refresh:
        if st.button("🔄 Refresh", use_container_width=True):
            st.rerun()

    with st.spinner("Loading history..."):
        data = api.get_ai_history()

    if "error" in data:
        st.error(f"Failed to load history: {data['error']}")
        return

    history = data.get("history", [])
    if not history:
        st.markdown('<div class="fin-card" style="text-align:center;padding:3rem;"><div style="font-size:2rem;">🕐</div><div style="color:#94a3b8;">No AI-generated content yet. Use Settlement Predictor or Negotiation Email to generate content.</div></div>', unsafe_allow_html=True)
        return

    st.markdown(f"<div style='color:#94a3b8;font-size:0.875rem;margin-bottom:1rem;'>{len(history)} item(s) found</div>", unsafe_allow_html=True)

    TYPE_COLORS = {"Negotiation Strategy":"#3b82f6","Negotiation Letter":"#10b981"}
    TYPE_ICONS  = {"Negotiation Strategy":"🎯","Negotiation Letter":"✉️"}

    for item in history:
        q_type = item.get("query_type","Unknown")
        color = TYPE_COLORS.get(q_type,"#8b5cf6")
        icon  = TYPE_ICONS.get(q_type,"🤖")
        ts      = _format_ts(item.get("timestamp"))
        content = item.get("generated_content","")
        with st.expander(f"{icon}  {q_type}  —  {ts}"):
            st.markdown(f"""
            <div style="display:flex;gap:0.75rem;align-items:center;margin-bottom:1rem;">
              <span class="badge" style="background:rgba(255,255,255,0.05);color:{color};border:1px solid {color}40;">{q_type}</span>
              <span style="font-size:0.8rem;color:#475569;">{ts}</span>
            </div>
            <div class="letter-box" style="max-height:400px;">{content}</div>
            """, unsafe_allow_html=True)
            st.download_button(
                label="⬇ Download", data=content,
                file_name=f"{q_type.replace(' ','_')}_{item.get('history_id','')}.txt",
                mime="text/plain", key=f"dl_{item.get('history_id','')}",
            )
